kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: manual
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: none
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels: 
    app: postgres
spec:
  storageClassName: manual
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests:
      storage: 2Gi