apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 35672
    - name: amqp
      protocol: TCP
      port: 5672
  selector: 
    app: rabbitmq